---
homebrew_installed_packages:
  - windmilleng/tap/tilt
  - docker-machine-driver-hyperkit

  - kubernetes-cli # kubectl for interaction with kubernetes clusters
  - kustomize # for building/handling/changing kubernetes manifests

  - ansible

  - exiftool # show/mutate EXIF information of documents
  - pstree # show parent/child relationship of processes

  - git
  - gpg2
  - git-crypt

  - mas
  - redis

  - asdf # language manager, Ruby/NodeJS/Golang/etc

  - rcm # tool for managing dotfiles

  # Terminal
  - direnv
  - fzf
  - fd # fast alternative to find (https://github.com/sharkdp/fd)
  - zsh # brew version of zsh

  - v8@3.15 # the ruby racer gem
  - gcc # To be able to compile libv8 with libc++
  - pkg-config # Helper tool for compiling applications
  - imagemagick # otherwise Rails image upload no work

  - dnsmasq
  - cdrtools # contains mkisofs for making cloud-init images
  - minikube # for running kubernetes locally
  - hyperkit # running virtual machines on macos for testing
  - hivemind # for running multiple virtual machines from procfile
  - dnsmasq # for custom DNS / DHCP
  - dhcping # for debugging DHCP responses

  - nektos/tap/act # For running GitHub actions locally
  - semaphoreci/tap/sem # Semaphore CI command line tool

  - { name: emacs-plus@28, install_options: 'with-spacemacs-icon' }
  - aspell # spellchecking
  - ag # silversearcher
  - ripgrep # search
  - ack # search
  - pt # the platinum searcher
  - cmake # for loading vterm
  - libvterm # vterm shell inside emacs
  - shellcheck # lint shell-script files

  # Networking tools
  - nmap
  - iperf

  # For generating and reading graphs using `dot` tool
  - graphviz

  # GNU tools instead of macos ones
  - coreutils
  - diffutils
  - findutils
  - gawk
  - gnu-indent
  - gnu-sed
  - gnu-tar
  - gnu-which
  - gnutls
  - grep
  - gzip
  - screen
  - watch
  - wdiff
  - wget

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/services
  - windmilleng/tap
  - d12frosted/emacs-plus

homebrew_cask_appdir: /Applications

homebrew_cask_apps:
  - visual-studio-code
  - multipass
  - amethyst
  - ngrok
  - virtualbox
  - gpg-suite
  - 1password-cli
  - steam
  - { name: iterm2, install_options: 'force' }
  - rubymine
  - adobe-creative-cloud
  - alfred # advanced alternative to macos spotlight
  - postman # for doing API calls
  - balenaetcher # utility for flashing disk images to sd card for raspberry pi

  # # TODO: force reload of the installed fonts (by manually installing one)
  # # will make these fonts available
  - font-source-code-pro
  - font-source-code-pro-for-powerline
  - font-menlo-for-powerline
  - font-fira-mono

# Use `mas search <<appname>>` to get the id and name
mas_installed_apps:
  - { id: 1147396723, name: "WhatsApp Desktop" }
  - { id: 585829637, name: "Todoist: To-Do List & Tasks" }
  - { id: 747648890, name: "Telegram" }
  - { id: 1404231964, name: "UPRIGHT GO Desktop" }

mas_upgrade_all_apps: true
mas_signin_dialog: true

languages:
  golang:
    global: 1.13
    versions:
      - version: 1.13
        packages: []

  nodejs:
    packages:
      - name: yarn # package manager
      - name: tern # spacemacs javascript layer
      - name: eslint_d # daemon for eslint
      - name: eslint # linting in javascript
      - name: eslint-plugin-graphql # linting in javascript
      - name: prettier # spacemacs javascript autofixer
      - name: fx # json viewer for the terminal
      - name: vmd # spacemacs markdown layer
      - name: import-js # spacemacs automatic import helper
      - name: typescript-language-server # lsp for javascript
      - name: typescript # typescript
      - name: speedscope # profiling presentation
      - name: depcheck # tool for checking used dependencies in a JS project
    global: 12.18.4
    versions:
      - version: 12.18.4
        packages: []

  ruby:
    gems:
      - name: pry
      - name: pry-doc
      - name: ruby_parser
      - name: seeing_is_believing
      - name: solargraph
      - name: ruby-debug-ide
      - name: debase
      - name: razor-client # for communication with the razor-server
      - name: mkpasswd # for generating password hashes for cloud-init
      - name: mailcatcher # email server to send local development emails to
      - name: git-merge-structure-sql # good merge strategy for structure.sql files
    global: 2.6.6
    versions:
      - version: 2.6.6
        # There is no 2.6.6 available in `solargraph available-cores`
        solargraph: 2.6.5
        gems:
          - { name: bundler, version: 2.1.4 }
          - { name: rubocop, version: 0.79.0 }
