---
homebrew_installed_packages:
  - windmilleng/tap/tilt
  - docker-machine-driver-hyperkit
  - kubernetes-cli
  - ansible

  - exiftool # show/mutate EXIF information of documents
  - pstree # show parent/child relationship of processes

  - git
  - gpg2
  - git-crypt

  - mas
  - redis

  # Terminal
  - direnv
  - fzf
  - fd # fast alternative to find (https://github.com/sharkdp/fd)
  - zsh # brew version of zsh

  - v8@3.15 # the ruby racer gem
  - imagemagick # otherwise Rails image upload no work

  - lastpass-cli

  - dnsmasq

  - packer # creating images for Vagrant

  # Emacs
  - emacs-plus
  - aspell # spellchecking
  - ag # silversearcher
  - ripgrep # search
  - ack # search
  - pt # the platinum searcher
  - cmake # for loading vterm
  - libvterm # vterm shell inside emacs
  - shellcheck # lint shell-script files

  # Networking tools
  - nmap
  - iperf

  # For generating and reading graphs using `dot` tool
  - graphviz

  # GNU tools instead of macos ones
  - coreutils
  - diffutils
  - findutils
  - gawk
  - gnu-indent
  - gnu-sed
  - gnu-tar
  - gnu-which
  - gnutls
  - grep
  - gzip
  - screen
  - watch
  - wdiff
  - wget

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/services
  - windmilleng/tap
  - d12frosted/emacs-plus

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - minikube
  - multipass
  - ngrok
  - virtualbox
  - vagrant
  - vagrant-manager
  - gpg-suite
  - 1password-cli
  - steam
  - iterm2

  # TODO: force reload of the installed fonts (by manually installing one)
  # will make these fonts available
  - font-source-code-pro
  - font-source-code-pro-for-powerline
  - font-menlo-for-powerline

# Use `mas search <<appname>>` to get the id and name
mas_installed_apps:
  - { id: 1147396723, name: "WhatsApp Desktop" }
  - { id: 585829637, name: "Todoist: To-Do List & Tasks" }
  - { id: 747648890, name: "Telegram" }
  - { id: 1404231964, name: "UPRIGHT GO Desktop" }

mas_upgrade_all_apps: true
mas_signin_dialog: true

languages:
  nodejs:
    packages:
      - name: yarn # package manager
      - name: tern # spacemacs javascript layer
      - name: eslint_d # daemon for eslint
      - name: eslint # linting in javascript
      - name: prettier # spacemacs javascript autofixer
      - name: fx # json viewer for the terminal
      - name: vmd # spacemacs markdown layer
      - name: import-js # spacemacs automatic import helper
      - name: typescript-language-server # lsp for javascript
      - name: typescript # typescript
    global: 12.13.0
    versions:
      - version: 12.13.0
        packages: []
      - version: 12.0.0
        packages: []
      - version: 10.16.3
        packages: []

  ruby:
    gems:
      - name: pry
      - name: pry-doc
      - name: ruby_parser
      - name: seeing_is_believing
      - name: solargraph
      - name: ruby-debug-ide
      - name: debase
    global: 2.6.5
    versions:
      - version: 2.6.5
        # There is no 2.6.5 available in `solargraph available-cores`
        solargraph: 2.6.1
        gems:
          - { name: bundler, version: 1.17.3 }
          - { name: rubocop, version: 0.73.0 }
      - version: 2.5.3
        solargraph: 2.5.3
        gems:
          - { name: bundler, version: 2.0.1 }
          - { name: rubocop }
