apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflare-tunnel-api-token
  namespace: cloudflare-tunnel
spec:
  itemPath: vaults/enigma-cluster/items/cloudflare-tunnel-ingress-controller
