# Common role configuration
common_hostname: peace-at-last

# Networking (bridge with static IP)
network_interface: eth0
ip_address: 192.168.1.15
gateway: 192.168.1.1
nameservers:
  - 192.168.1.1

# SSH public key for maarten user
maarten_user_public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKbI3UZOhsVGi1lbnH7Sd0KWtP5m6zUJgrxbHMTxhRcW
