# trunk-ignore-all(yamllint/syntax)
# trunk-ignore-all(prettier/SyntaxError)
# Become password for sudo operations
ansible_become_pass: op://setup-pihole-prod/maarten-pihole/password
# Encrypted passwords for Ansible user module
maarten_user_password_encrypted: op://setup-pihole-prod/maarten-pihole/password_encrypted
root_user_password_encrypted: op://setup-pihole-prod/root-pihole/password_encrypted
# Pi-hole web interface password
pihole_web_password: op://setup-pihole-prod/pihole-web/password
