# Common role configuration
common_hostname: peace-at-last

# Networking (bridge with static IP)
network_interface: eth0
ip_address: 192.168.1.15
gateway: 192.168.1.1
nameservers:
  - 192.168.1.1

# SSH public key for maarten user
maarten_user_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAvXN6EpJc9+19awLUuqdVvvjZ1v/ofx9dee9UzM3xXp"

# Pi-hole VLAN 50 configuration
pihole_vlan50_ip: 192.168.50.2
pihole_vlan50_gateway: 192.168.50.1
pihole_vlan50_parent_interface: eth0.50
pihole_vlan50_subnet: 192.168.50.0/24

# Pi-hole Admin LAN configuration
pihole_admin_ip: 192.168.1.16
pihole_admin_gateway: 192.168.1.1
pihole_admin_parent_interface: br0
pihole_admin_subnet: 192.168.1.0/24

# Shared Pi-hole configuration
pihole_upstream_dns: 192.168.1.1
pihole_timezone: Europe/Amsterdam

# DNS records for *.enigma.vgijssel.nl
pihole_dns_records:
  - { ip: "192.168.50.100", domain: "dashboard.enigma.vgijssel.nl" }
  - { ip: "192.168.50.100", domain: "keycloak.enigma.vgijssel.nl" }
  - { ip: "192.168.50.100", domain: "api.enigma.vgijssel.nl" }
  - { ip: "192.168.50.100", domain: "pikvm.enigma.vgijssel.nl" }
  - { ip: "192.168.50.100", domain: "bucket-terraform.enigma.vgijssel.nl" }
  - { ip: "192.168.50.100", domain: "coder.enigma.vgijssel.nl" }
  - { ip: "192.168.50.100", domain: "s3.enigma.vgijssel.nl" }
  - {
      ip: "192.168.50.100",
      domain: "kubernetes-coder-cluster-prod.enigma.vgijssel.nl",
    }
