apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-helmreleases
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: setup
  path: ./stacks/enigma-cluster/apps/helmreleases
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
    - name: apps-configs
