apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-flux-system.yaml
  - gitrepository-setup.yaml
  - kustomization-root.yaml
  - kustomization-infrastructure-helmreleases.yaml
  - kustomization-infrastructure-configs.yaml
  - kustomization-apps-configs.yaml
  - kustomization-apps-helmreleases.yaml
