apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-flux-system.yaml
  - gitrepository-setup.yaml
  - kustomization-root.yaml
  - kustomization-helmreleases.yaml
  - kustomization-configs.yaml
