apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # FluxCD source
  - gitrepository-setup.yaml
  - kustomization-root.yaml
  # CozyStack VM resources
  - vmdisk-haos.yaml
  - vminstance-haos.yaml
  # Kyverno policies
  - kyverno-policy-virtual-machine-patches.yaml
