apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: docs-prod
  namespace: cozy-fluxcd
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: setup
  path: ./apps/docs-prod
  prune: true
  wait: true
  timeout: 10m
