apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - onepasswordsecret-cloudflare-api-token.yaml
  - onepasswordsecret-cloudflare-tunnel.yaml
  - onepasswordsecret-external-dns.yaml
  - onepasswordsecret-tailscale-operator.yaml
