apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: external-dns-cloudflare-api-token
  namespace: external-dns
spec:
  itemPath: vaults/enigma-cluster/items/cloudflare-external-dns
