apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # FluxCD source
  - gitrepository-setup.yaml
  - kustomization-root.yaml
  # KubeVirt VM preferences
  - vmclusterpreference-haos.yaml
  # CozyStack VM resources
  - vmdisk-haos.yaml
  - vminstance-haos.yaml
