apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: haos-enigma
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: haos-enigma
  path: ./apps/haos-enigma
  prune: true
  wait: true
  timeout: 15m
