$schema: ../cache/schemas/tasks.json
fileGroups:
  pnpm_bin:
    - /bin/pnpm
    - /bin/.pnpm-*
    - /bin/hermit

  vendir_bin:
    - /bin/vendir
    - /bin/.vendir-*
    - /bin/hermit

  regctl_bin:
    - /bin/regctl
    - /bin/.regctl-*
    - /bin/hermit
