$schema: ../cache/schemas/tasks.json
fileGroups:
  pnpm_bin:
    - /bin/pnpm
    - /bin/.pnpm-*
    - /bin/hermit

  vendir_bin:
    - /bin/vendir
    - /bin/.vendir-*
    - /bin/hermit

  regctl_bin:
    - /bin/regctl
    - /bin/.regctl-*
    - /bin/hermit

  chezmoi_bin:
    - /bin/chezmoi
    - /bin/.chezmoi-*
    - /bin/hermit
    - /bin/chezmoi-wrapper

  code-server_bin:
    - /bin/code-server
    - /bin/.code-server-*
    - /bin/hermit

  node_bin:
    - /bin/node
    - /bin/.node-*
    - /bin/hermit

  python_bin:
    - /bin/python3
    - /bin/.python3-*
    - /bin/hermit

  hermit_bundle_bin:
    - /bin/hermit-bundle
    - /bin/hermit
