$schema: ../cache/schemas/tasks.json
fileGroups:
  pnpm_bin:
    - /bin/pnpm
    - /bin/.pnpm-*
    - /bin/hermit

  vendir_bin:
    - /bin/vendir
    - /bin/.vendir-*
    - /bin/hermit

  regctl_bin:
    - /bin/regctl
    - /bin/.regctl-*
    - /bin/hermit

  chezmoi_bin:
    - /bin/chezmoi
    - /bin/.chezmoi-*
    - /bin/hermit
    - /bin/chezmoi-wrapper

  claude_bin:
    - /bin/claude
    - /bin/.claude-code-*
    - /bin/hermit
