substitutions:
  name: "baby-room-ultimate"
  friendly_name: "Baby Room Ultimate"
  relay_count: "1"

  device_name: baby-room-ultimate
  entity_id: baby_room_ultimate
  static_ip: 192.168.1.86

packages:
  base: !include .base.yaml
  smarthomeyourself.tx-ultimate: github://SmartHome-yourself/sonoff-tx-ultimate-for-esphome/tx_ultimate.yaml@main
