substitutions:
  device_name: landing-shelly
  entity_id: landing_shelly
  light_entity_id: light.landing_lights
  room_name: landing
  static_ip: 192.168.1.67

packages:
  device_base: !include .shelly-1pm-plus.yaml
  # bluetooth_object_tracking: !include .bluetooth_object_tracking.yaml
  base: !include .base.yaml
  # smart_light_restore: !include .smart_light_restore.yaml

binary_sensor:
  - <<: !include .smart_light_binary_sensor.yaml
    name: ${entity_id}_input
    pin: GPIO4
  - platform: homeassistant
    id: light_sensor
    entity_id: ${light_entity_id}
  - <<: !include .verjaardag_hilde_lights_override.yaml
