substitutions:
  device_name: supply-closet-shelly
  entity_id: supply_closet_shelly
  room_name: supply_closet
  static_ip: 192.168.1.71

packages:
  device_base: !include .shelly-1pm-plus.yaml
  # bluetooth_object_tracking: !include .bluetooth_object_tracking.yaml
  base: !include .base.yaml

binary_sensor:
  - <<: !include .basic_light_binary_sensor.yaml
    name: ${entity_id}_input
    pin: GPIO4
  - <<: !include .verjaardag_hilde_lights_override.yaml
