apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: docs-infra-prod
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: docs-infra-prod
  path: ./apps/docs-infra-prod
  prune: true
  wait: true
  timeout: 10m
