apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: virtual-ingress
  namespace: flux-system
spec:
  interval: 30m
  dependsOn:
    - name: kyverno
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: libs/virtual-ingress
      sourceRef:
        kind: GitRepository
        name: setup
        namespace: flux-system
      interval: 12h
      reconcileStrategy: Revision
  targetNamespace: kyverno
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    kyvernoNamespace: kyverno
    serviceDiscovery:
      noMatchBehavior: error
      multipleMatchBehavior: error
