apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: enigma-cluster
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: setup
  path: ./stacks/enigma-cluster
  prune: true
  wait: true
  timeout: 10m
