apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gitrepository-setup.yaml
  - kustomization-root.yaml
  - cozystack.yaml
  - storageclasses.yaml
  - metallb-ip-address-pool.yml
  - metallb-l2-advertisement.yml
  - helmrelease-1password-operator.yaml
  - helmrelease-1password-secrets.yaml
  - helmrelease-kyverno.yaml
  - clusterpolicy-multus-memory.yaml
  - clusterpolicy-linstor-nodeselector.yaml
  - helmrelease-internal-networking.yaml
  - helmrelease-underlay-networking.yaml
  - helmrelease-external-service.yaml
  - helmrelease-external-dns.yaml
  - helmrelease-external-dns-pihole.yaml
  - namespace-tailscale.yaml
  - helmrelease-tailscale-operator.yaml
  - namespace-ingress-nginx-gateway.yaml
  - helmrelease-ingress-nginx-gateway.yaml
  - job-linstor-interfaces.yaml
  - job-linstor-node-connections.yaml
  - job-linstor-drbd-options.yaml
