apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-flux-system.yaml
  - gitrepository-setup.yaml
  - kustomization-root.yaml
  - helmrelease-1password-operator.yaml
  - helmrelease-1password-secrets.yaml
  - helmrelease-kyverno.yaml
  - clusterpolicy-multus-memory.yaml
  - helmrelease-internal-networking.yaml
  - helmrelease-external-dns.yaml
  - helmrelease-tailscale-operator.yaml
  - namespace-ingress-nginx-gateway.yaml
  - helmrelease-ingress-nginx-gateway.yaml
